version: '3'
services:
  app:
    image: webdevops/php-nginx
    ports:
      - "80:80"
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
    volumes:
      - .:/var/www/html
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: reporte_gei
      POSTGRES_PASSWORD: osvaldo1249
      POSTGRES_DB: atacama_development
    volumes:
      - pgdata:/var/lib/postgresql/data
  admin:
    image: adminer
    ports:
      - 8080:8080
volumes:
  pgdata: